name: 'AquaSec Scan Results'
description: 'Process and handle AquaSec security scan results for GitHub Security tab integration'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  aqua-key:
    description: 'AquaSec API Key'
    required: true
  aqua-secret:
    description: 'AquaSec API Secret'
    required: true

outputs:
  bearer-token:
    description: 'AquaSec Bearer Token for authentication'
    value: ${{ steps.authenticate.outputs.bearer-token }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate with AquaSec
      id: authenticate
      run: python3 ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_AQUA-KEY: ${{ inputs.aqua-key }}
        INPUT_AQUA-SECRET: ${{ inputs.aqua-secret }}
