name: 'AquaSec Scan Results'
description: 'Process and handle AquaSec security scan results for GitHub Security tab integration'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  aqua-key:
    description: 'AquaSec API Key'
    required: true
  aqua-secret:
    description: 'AquaSec API Secret'
    required: true
  repository-id:
    description: 'AquaSec Repository ID (UUID format)'
    required: true
  verbose-logging:
    description: 'Enable or disable verbose logging.'
    required: false
    default: 'false'

outputs:
  scan-findings:
    description: 'JSON containing all AquaSec security scan findings'
    value: ${{ steps.aquasec-scan-results.outputs.scan_findings }}

runs:
  using: 'composite'
  steps:
    - name: Install Python dependencies
      run: |
        python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Prepare environment variables
      run: |
        echo "::add-mask::${{ inputs.aqua-key }}"
        echo "::add-mask::${{ inputs.aqua-secret }}"
        echo "::add-mask::${{ inputs.repository-id }}"
        echo "INPUT_AQUA_KEY=${{ inputs.aqua-key }}" >> $GITHUB_ENV
        echo "INPUT_AQUA_SECRET=${{ inputs.aqua-secret }}" >> $GITHUB_ENV
        echo "INPUT_REPOSITORY_ID=${{ inputs.repository-id }}" >> $GITHUB_ENV
        echo "INPUT_VERBOSE_LOGGING=${{ inputs.verbose-logging }}" >> $GITHUB_ENV
      shell: bash

    - name: Run AquaSec Scan Results action
      id: aquasec-scan-results
      env:
        INPUT_AQUA_KEY: ${{ env.INPUT_AQUA_KEY }}
        INPUT_AQUA_SECRET: ${{ env.INPUT_AQUA_SECRET }}
        INPUT_REPOSITORY_ID: ${{ env.INPUT_REPOSITORY_ID }}
        INPUT_VERBOSE_LOGGING: ${{ env.INPUT_VERBOSE_LOGGING }}
      run: |
        export PYTHONPATH="${PYTHONPATH}:${{ github.action_path }}"
        python3 ${{ github.action_path }}/main.py
      shell: bash
