name: 'AquaSec Scan Results'
description: 'Process and handle AquaSec security scan results for GitHub Security tab integration'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  aqua-key:
    description: 'AquaSec API Key'
    required: true
  aqua-secret:
    description: 'AquaSec API Secret'
    required: true
  verbose-logging:
    description: 'Enable or disable verbose logging.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Python dependencies
      run: |
        python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Prepare environment variables
      run: |
        echo "INPUT_AQUA_KEY=${{ inputs.aqua-key }}" >> $GITHUB_ENV
        echo "INPUT_AQUA_SECRET=${{ inputs.aqua-secret }}" >> $GITHUB_ENV
        echo "INPUT_VERBOSE_LOGGING=${{ inputs.verbose-logging }}" >> $GITHUB_ENV
      shell: bash

    - name: Run AquaSec Scan Results action
      id: aquasec-scan-results
      env:
        INPUT_AQUA_KEY: ${{ env.INPUT_AQUA_KEY }}
        INPUT_AQUA_SECRET: ${{ env.INPUT_AQUA_SECRET }}
        INPUT_VERBOSE_LOGGING: ${{ env.INPUT_VERBOSE_LOGGING }}
      run: |
        export PYTHONPATH="${PYTHONPATH}:${{ github.action_path }}"
        python3 ${{ github.action_path }}/main.py
      shell: bash
